theme: jekyll-theme-minimal
show_downloads: true
title: Automated Tunability Evaluation using Linear Variable Filter
logo: p-active-logo.jpeg
description: A MATLAB GUI for automated phase-changing and measurement.
github:
  zip_url: https://github.com/dbombara/reliability_test
  tar_url: https://github.com/mdelmans/reliability_test
